# Generated by Django 3.1 on 2020-10-21 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_webauthorizationrecord_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='地址')),
                ('port', models.CharField(max_length=10, verbose_name='端口')),
                ('user', models.CharField(max_length=30, verbose_name='用户')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('ldap_server', models.CharField(default='openladp', max_length=30)),
                ('use_ssl', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='login_ip',
            field=models.CharField(default='', max_length=40, verbose_name='最后登录ip'),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='login_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='source',
            field=models.CharField(choices=[('local', '本地登录'), ('ldap', 'LDAP登录'), ('ding', '钉钉登录')], default='local', max_length=30, verbose_name='最后登录方式'),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
