# Generated by Django 3.1 on 2020-10-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201021_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, default='local', max_length=10, null=True),
        ),
    ]
