# Generated by Django 3.1 on 2020-10-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_ldapuseremailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapserver',
            name='ldap_server',
            field=models.CharField(choices=[('openladp', 'openladp'), ('windows_ad', 'windows_ad')], max_length=30, verbose_name='ldap类型'),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='password',
            field=models.CharField(max_length=30, verbose_name='管理密码'),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='user',
            field=models.CharField(max_length=30, verbose_name='管理用户'),
        ),
    ]
