# Generated by Django 3.1 on 2020-10-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201025_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapserver',
            name='password',
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='_password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
