# Generated by Django 3.1 on 2020-10-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_ldapserver_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogininfo',
            name='ldap_server',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='desc',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='描述'),
        ),
    ]
