# Generated by Django 3.1 on 2020-10-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201026_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapuseremailverifyrecord',
            name='ldap_server_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ldap服务id'),
        ),
    ]
