# Generated by Django 3.1 on 2020-10-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20201027_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapuseremailverifyrecord',
            name='ldap_base_dn',
        ),
        migrations.RemoveField(
            model_name='ldapuseremailverifyrecord',
            name='ldap_group_dn',
        ),
        migrations.RemoveField(
            model_name='ldapuseremailverifyrecord',
            name='ldap_group_object_class',
        ),
        migrations.RemoveField(
            model_name='ldapuseremailverifyrecord',
            name='ldap_user_dn',
        ),
        migrations.RemoveField(
            model_name='ldapuseremailverifyrecord',
            name='ldap_user_object_class',
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='ldap_base_dn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='基本DN'),
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='ldap_group_dn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='附加组DN'),
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='ldap_group_object_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='组对象类'),
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='ldap_user_dn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='附加用户DN'),
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='ldap_user_object_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户对象类'),
        ),
    ]
