# Generated by Django 3.1 on 2020-10-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20201027_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapserver',
            name='ldap_group_object_class',
            field=models.CharField(blank=True, choices=[('groupOfUniqueNames', 'groupOfUniqueNames')], max_length=50, null=True, verbose_name='组对象类'),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='ldap_user_object_class',
            field=models.CharField(blank=True, choices=[('inetOrgPerson', 'inetOrgPerson')], max_length=50, null=True, verbose_name='用户对象类'),
        ),
    ]
