# Generated by Django 3.1 on 2021-01-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20201109_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='权限名称名称')),
                ('mark', models.CharField(max_length=20, unique=True, verbose_name='权限简称')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='external_permission',
            field=models.ManyToManyField(blank=True, to='accounts.ExternalPermission', verbose_name='拥有的权限'),
        ),
    ]
